name: Daily itch.io Release
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes to test 
  workflow_dispatch:

jobs:
  export-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Godot
        uses: pinkeyu7/setup-godot@v1
        with:
          version: 4.3

      - name: Set Build Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Create Exports Directory
        run: mkdir -p exports

      - name: Build Web Export
        run: |
          godot --headless --export-release "Web" ./exports/index.html
        continue-on-error: true

      - name: Verify Export Directory
        run: ls -lah ./exports

      - name: Zip Web Build
        run: |
          cd exports
          zip -r web_build.zip .

      - name: Install Butler
        run: |
          curl -L -o butler https://broth.itch.ovh/butler/linux-amd64/LATEST/butler
          chmod +x butler
          ./butler -V

      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push ./exports/web_build.zip yelendrey/band-together:web-build --userversion=${{ steps.date.outputs.date }}