name: Godot Web Export and itch.io Deploy
on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/4.3.stable
          curl -L https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz --output export_templates.tpz
          unzip export_templates.tpz -d ~/.local/share/godot/export_templates/4.3.stable
          rm export_templates.tpz

      - name: Import project
        run: |
          cd band_together
          mkdir -v -p .godot/imported
          godot --headless --script import_project.gd

      - name: Web Build
        run: |
          cd band_together
          mkdir -v -p ../build/web
          godot --headless --export-release "Web" ../build/web/index.html

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push ./build/web yelendrey/band-together:web --userversion=$(date -u +"%Y-%m-%d-%H:%M:%S")