name: Godot Web Export and Deploy
on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --export-release "Web" ./build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build/web

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push ./build/web yelendrey/band-together:web --userversion=$(date -u +"%Y-%m-%d-%H:%M:%S")
