name: Godot Web Export and itch.io Deploy
on:
  schedule:
    - cron: '0 15 * * *'  # Run every day at 9:00 AM MDT (15:00 UTC)
  workflow_dispatch:
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.3.stable
          mv /root/.local/share/godot/export_templates/4.3.stable/* ~/.local/share/godot/export_templates/4.3.stable/
      - name: Check Godot Version
        run: |
          godot --version
          echo "Godot version should match 4.3"
      - name: Web Build
        run: |
          cd band_together
          mkdir -v -p ../build/web
          godot --headless --export-release "Web" ../build/web/index.html
          cp -r addons ../build/web/
          ls -R ../build/web
      - name: Install Butler
        run: |
          wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          mv butler /usr/local/bin/butler
      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          cd band_together
          butler push ../build/web yelendrey/band-together:web --verbose --userversion=$(date -u +"%Y-%m-%d-%H:%M:%S")